language: python
os: linux
dist: bionic

cache:
  pip: true
  cargo: true

env:
  global:
    - TRAVIS_RUST_VERSION=stable
    - RUST_BACKTRACE=1

jobs:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
      env: RUN_LINT=1
    - name: MSRV
      python: "3.8"
      env: TRAVIS_RUST_VERSION=1.39.0

addons:
  apt:
    packages:
      - gfortran

before_install:
  - source ./ci/travis/setup.sh

install:
  - pip install setuptools-rust pytest tox numpy flake8

script:
  - flake8 examples/
  - ./ci/travis/test.sh

deploy:
  - provider: script
    skip-cleanup: true
    script: ./ci/travis/deploy.sh
    on:
      branch: master
      repo: rust-numpy/rust-numpy
      python: 3.6

